#!/bin/sh
SERVICE_NAME=arcbot
INSTANCE_NAME=marc
PATH_TO_JAR=/usr/local/$SERVICE_NAME/toolsbox.jar
PID_PATH_NAME=/usr/local/$SERVICE_NAME/$SERVICE_NAME-$INSTANCE_NAME-pid
ORIGIN_FOLDER=/media/data4/MarcIphone
DESTINATION_FOLDER=/media/data3/Archived/FamilyPhotos
LOG_FILENAME=/usr/local/$SERVICE_NAME/$INSTANCE_NAME
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java -jar $PATH_TO_JAR $ORIGIN_FOLDER $DESTINATION_FOLDER > $LOG_FILENAME.log 2>&1 &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup java -jar $PATH_TO_JAR $ORIGIN_FOLDER $DESTINATION_FOLDER > $LOG_FILENAME.log 2>&1 &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac